#: ============================================================
#: Color Scheme Kitty Terminal - Graffiti ZX0R Theme
#: ============================================================

# The basic colors
foreground            #e0f7fc
background            #000000

selection_foreground  #000000
selection_background  #00b4ff

# Kitty window border colors
active_border_color   #00b4ff
inactive_border_color #333333
bell_border_color     #ff003c

# Tab bar colors
tab_bar_background none

active_tab_background   #000000
active_tab_foreground   #00ff66
inactive_tab_background #222222
inactive_tab_foreground #888888

# Colors for marks (marked text in the terminal)
mark1_foreground #000000
mark1_background #00b4ff
mark2_foreground #000000
mark2_background #ff7700
mark3_foreground #000000
mark3_background #ff003c

# The 16 terminal colors
# black
color0 #333333
color8 #555555

# red
color1  #ff003c
color9  #ff2a2a

# green
color2  #00ff66
color10 #00ff00

# yellow
color3  #ffaa00
color11 #ffcc00

# blue
color4  #00b4ff
color12 #67cbff

# magenta
color5  #ff007f
color13 #fd00ff

# cyan
color6  #00ffff
color14 #26feff

# white
color7  #e0f7fc
color15 #ffffff

# Cursor colors
cursor            #ff7700
cursor_text_color #000000

# URL underline color when hovering with mouse
url_color #00ffff
